Repository PizzaCola-K/todo-list, pull requests merged in 2021-04, with the labels that each got.

#9 Mock API (GET)
  README.md
  backend/src/main/java/com/team13/todolist/controller/ActivityController.java
  backend/src/main/java/com/team13/todolist/controller/CardController.java
  backend/src/main/java/com/team13/todolist/controller/ColumnController.java
  backend/src/main/java/com/team13/todolist/model/Activity.java
  backend/src/main/java/com/team13/todolist/model/Card.java
  backend/src/main/java/com/team13/todolist/model/Column.java
  backend/src/main/java/com/team13/todolist/model/User.java
  backend/src/main/java/com/team13/todolist/repository/ActivityRepository.java
  backend/src/main/java/com/team13/todolist/repository/CardRepository.java
  backend/src/main/java/com/team13/todolist/repository/ColumnRepository.java
  backend/src/main/java/com/team13/todolist/service/ActivityService.java
  backend/src/main/java/com/team13/todolist/service/CardService.java
  backend/src/main/java/com/team13/todolist/service/ColumnService.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/team13/todolist/repository/CardRepositoryTest.java
  backend/src/test/resources/application-test.properties
Labels: BE, enhancement

#11 First Deploy
  README.md
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/team13/todolist/ToDoListApplication.java
  backend/src/main/java/com/team13/todolist/controller/ActivityController.java
  backend/src/main/java/com/team13/todolist/controller/CardController.java
  backend/src/main/java/com/team13/todolist/controller/ColumnController.java
  backend/src/main/java/com/team13/todolist/model/Activity.java
  backend/src/main/java/com/team13/todolist/model/Card.java
  backend/src/main/java/com/team13/todolist/model/Column.java
  backend/src/main/java/com/team13/todolist/model/User.java
  backend/src/main/java/com/team13/todolist/repository/ActivityRepository.java
  backend/src/main/java/com/team13/todolist/repository/CardRepository.java
  backend/src/main/java/com/team13/todolist/repository/ColumnRepository.java
  backend/src/main/java/com/team13/todolist/service/ActivityService.java
  backend/src/main/java/com/team13/todolist/service/CardService.java
  backend/src/main/java/com/team13/todolist/service/ColumnService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/team13/todolist/ToDoListApplicationTests.java
  backend/src/test/java/com/team13/todolist/repository/CardRepositoryTest.java
  backend/src/test/resources/application-test.properties
Labels: BE

#12 [FE] Complete CardInput component
  frontend/src/components/Seong/ButtonAccent.js
  frontend/src/components/Seong/ButtonNomal.js
  frontend/src/components/Seong/CardInput.js
Labels: FE

#13 [FE] Complete Card component
  frontend/src/App.js
  frontend/src/components/Seong/ButtonNomal.js
  frontend/src/components/Seong/Card.js
  frontend/src/components/Seong/CardInput.js
  frontend/src/components/Seong/Column.js
Labels: FE

#16 [FE] Complete Activity component
  frontend/src/App.js
  frontend/src/components/common/StyledMain.js
  frontend/src/components/header/Activity.js
  frontend/src/components/header/Header.js
  frontend/src/components/header/SideLog.js
  frontend/src/components/header/partial/ActivityCloseButton.js
  frontend/src/components/header/partial/ActivityItem.js
  frontend/src/components/header/partial/HeaderMenuButton.js
  frontend/src/containers/header/HeaderContainer.js
Labels: FE

#20 [FE] Modify Column-related styles
  frontend/src/components/main/Card.js
  frontend/src/components/main/CardInput.js
  frontend/src/components/main/Column.js
  frontend/src/components/main/partial/ButtonAccent.js
  frontend/src/components/main/partial/ButtonNomal.js
  frontend/src/components/main/partial/ColumnAccentButton.js
  frontend/src/components/main/partial/ColumnDeleteButton.js
  frontend/src/components/main/partial/ColumnNormalButton.js
  frontend/src/components/main/partial/ColumnPlusButton.js
Labels: CSS, FE

#21 [FE] Refactor Column component
  frontend/src/components/main/Card.js
  frontend/src/components/main/CardInput.js
  frontend/src/components/main/Column.js
  frontend/src/containers/column/ColumnContainer.js
Labels: FE

#22 Fe dev
  frontend/src/App.js
  frontend/src/components/Test/TestTemplate.js
  frontend/src/components/common/StyledModels.js
  frontend/src/components/header/Activity.js
  frontend/src/components/header/Header.js
  frontend/src/components/header/partial/ActivityCloseButton.js
  frontend/src/components/header/partial/ActivityItem.js
  frontend/src/components/header/partial/HeaderMenuButton.js
  frontend/src/components/main/Card.js
  frontend/src/components/main/CardInput.js
  frontend/src/components/main/Column.js
  frontend/src/components/main/Main.js
  frontend/src/components/main/partial/ColumnAccentButton.js
  frontend/src/components/main/partial/ColumnDeleteButton.js
  frontend/src/components/main/partial/ColumnNormalButton.js
  frontend/src/components/main/partial/ColumnPlusButton.js
  frontend/src/containers/Test/TestContainer.js
  frontend/src/containers/column/ColumnContainer.js
  frontend/src/containers/header/HeaderContainer.js
  frontend/src/containers/main/MainContainer.js
  frontend/src/index.js
Labels: FE

#23 [FE] Implement communication feature
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/main/Card.js
  frontend/src/components/main/CardInput.js
  frontend/src/components/main/Column.js
  frontend/src/containers/column/ColumnContainer.js
  frontend/src/containers/header/HeaderContainer.js
  frontend/src/containers/main/MainContainer.js
  frontend/src/setupProxy.js
Labels: FE

#24 [FE] Header folder structure change and style modification
  frontend/public/images/smile.png
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/header/Activity/Activity.js
  frontend/src/components/header/Activity/ActivityCloseButton.js
  frontend/src/components/header/Activity/ActivityItem.js
  frontend/src/components/header/Header/Header.js
  frontend/src/components/header/Header/HeaderMenuButton.js
  frontend/src/components/header/HeaderTemplate.js
  frontend/src/components/header/partial/ActivityItem.js
  frontend/src/containers/header/HeaderContainer.js
  frontend/src/containers/main/MainContainer.js
Labels: CSS, FE

#25 Fe dev
  frontend/package.json
  frontend/public/images/smile.png
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/header/Activity/Activity.js
  frontend/src/components/header/Activity/ActivityCloseButton.js
  frontend/src/components/header/Activity/ActivityItem.js
  frontend/src/components/header/Header/Header.js
  frontend/src/components/header/Header/HeaderMenuButton.js
  frontend/src/components/header/HeaderTemplate.js
  frontend/src/components/header/partial/ActivityItem.js
  frontend/src/components/main/Card.js
  frontend/src/components/main/CardInput.js
  frontend/src/components/main/Column.js
  frontend/src/containers/column/ColumnContainer.js
  frontend/src/containers/header/HeaderContainer.js
  frontend/src/containers/main/MainContainer.js
  frontend/src/setupProxy.js
Labels: FE

#31 To Do List 기본 기능 구현
  backend/src/main/java/com/team13/todolist/controller/ActivityController.java
  backend/src/main/java/com/team13/todolist/controller/CardController.java
  backend/src/main/java/com/team13/todolist/controller/ColumnController.java
  backend/src/main/java/com/team13/todolist/model/Activity.java
  backend/src/main/java/com/team13/todolist/model/AddCardParameter.java
  backend/src/main/java/com/team13/todolist/model/Card.java
  backend/src/main/java/com/team13/todolist/model/CardInfo.java
  backend/src/main/java/com/team13/todolist/model/CardRef.java
  backend/src/main/java/com/team13/todolist/model/Column.java
  backend/src/main/java/com/team13/todolist/model/ColumnInfo.java
  backend/src/main/java/com/team13/todolist/model/UpdateCardParameter.java
  backend/src/main/java/com/team13/todolist/model/User.java
  backend/src/main/java/com/team13/todolist/repository/ActivityRepository.java
  backend/src/main/java/com/team13/todolist/service/ActivityService.java
  backend/src/main/java/com/team13/todolist/service/CardService.java
  backend/src/main/java/com/team13/todolist/service/ColumnService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/team13/todolist/ToDoListApplicationTests.java
  backend/src/test/java/com/team13/todolist/model/ColumnTest.java
  backend/src/test/java/com/team13/todolist/repository/CardRepositoryTest.java
  backend/src/test/java/com/team13/todolist/repository/ColumnRepositoryTest.java
  backend/src/test/java/com/team13/todolist/service/ColumnServiceTest.java
  backend/src/test/resources/application.properties
Labels: BE, enhancement

#32 Backend 배포를 위한 PR
  backend/src/main/java/com/team13/todolist/controller/ActivityController.java
  backend/src/main/java/com/team13/todolist/controller/CardController.java
  backend/src/main/java/com/team13/todolist/controller/ColumnController.java
  backend/src/main/java/com/team13/todolist/model/Activity.java
  backend/src/main/java/com/team13/todolist/model/AddCardParameter.java
  backend/src/main/java/com/team13/todolist/model/Card.java
  backend/src/main/java/com/team13/todolist/model/CardInfo.java
  backend/src/main/java/com/team13/todolist/model/CardRef.java
  backend/src/main/java/com/team13/todolist/model/Column.java
  backend/src/main/java/com/team13/todolist/model/ColumnInfo.java
  backend/src/main/java/com/team13/todolist/model/UpdateCardParameter.java
  backend/src/main/java/com/team13/todolist/model/User.java
  backend/src/main/java/com/team13/todolist/repository/ActivityRepository.java
  backend/src/main/java/com/team13/todolist/service/ActivityService.java
  backend/src/main/java/com/team13/todolist/service/CardService.java
  backend/src/main/java/com/team13/todolist/service/ColumnService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/team13/todolist/ToDoListApplicationTests.java
  backend/src/test/java/com/team13/todolist/model/ColumnTest.java
  backend/src/test/java/com/team13/todolist/repository/CardRepositoryTest.java
  backend/src/test/java/com/team13/todolist/repository/ColumnRepositoryTest.java
  backend/src/test/java/com/team13/todolist/service/ColumnServiceTest.java
  backend/src/test/resources/application.properties
Labels: BE, FE

#33 배포를 위한 Frontend PR
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/images/smile.png
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/common/StyledModels.js
  frontend/src/components/header/Activity/Activity.js
  frontend/src/components/header/Activity/ActivityCloseButton.js
  frontend/src/components/header/Activity/ActivityItem.js
  frontend/src/components/header/Header/Header.js
  frontend/src/components/header/Header/HeaderMenuButton.js
  frontend/src/components/header/HeaderTemplate.js
  frontend/src/components/main/Card.js
  frontend/src/components/main/CardInput.js
  frontend/src/components/main/Column.js
  frontend/src/components/main/Main.js
  frontend/src/components/main/partial/ColumnAccentButton.js
  frontend/src/components/main/partial/ColumnDeleteButton.js
  frontend/src/components/main/partial/ColumnNormalButton.js
  frontend/src/components/main/partial/ColumnPlusButton.js
  frontend/src/containers/column/ColumnContainer.js
  frontend/src/containers/header/HeaderContainer.js
  frontend/src/containers/main/MainContainer.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupProxy.js
  frontend/src/setupTests.js
Labels: BE, FE

#34 MySQL 연결
  README.md
  backend/build.gradle
  backend/src/main/java/com/team13/todolist/model/CardRef.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/team13/todolist/repository/CardRepositoryTest.java
  backend/src/test/java/com/team13/todolist/repository/ColumnRepositoryTest.java
  backend/src/test/java/com/team13/todolist/service/ColumnServiceTest.java
  backend/src/test/resources/application.properties
  backend/src/test/resources/data.sql
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/images/smile.png
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/common/StyledModels.js
  frontend/src/components/header/Activity/Activity.js
  frontend/src/components/header/Activity/ActivityCloseButton.js
  frontend/src/components/header/Activity/ActivityItem.js
  frontend/src/components/header/Header/Header.js
  frontend/src/components/header/Header/HeaderMenuButton.js
  frontend/src/components/header/HeaderTemplate.js
  frontend/src/components/main/Card.js
  frontend/src/components/main/CardInput.js
  frontend/src/components/main/Column.js
  frontend/src/components/main/Main.js
  frontend/src/components/main/partial/ColumnAccentButton.js
  frontend/src/components/main/partial/ColumnDeleteButton.js
  frontend/src/components/main/partial/ColumnNormalButton.js
  frontend/src/components/main/partial/ColumnPlusButton.js
  frontend/src/containers/column/ColumnContainer.js
  frontend/src/containers/header/HeaderContainer.js
  frontend/src/containers/main/MainContainer.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupProxy.js
  frontend/src/setupTests.js
Labels: BE, enhancement

#36 Fe integrate
  frontend/src/App.js
  frontend/src/components/common/AccentButton.js
  frontend/src/components/common/CommonStyledComponent.js
  frontend/src/components/common/NormalButton.js
  frontend/src/components/common/PopupModal.js
  frontend/src/components/header/Activity/ActivityItem.js
  frontend/src/components/main/Card.js
  frontend/src/components/main/CardInput.js
  frontend/src/components/main/Main.js
  frontend/src/components/main/column/Column.js
  frontend/src/components/main/column/ColumnDeleteButton.js
  frontend/src/components/main/column/ColumnPlusButton.js
  frontend/src/components/main/column/card/Card.js
  frontend/src/components/main/column/card/CardInput.js
  frontend/src/components/topbar/Activity/Activity.js
  frontend/src/components/topbar/Activity/ActivityCloseButton.js
  frontend/src/components/topbar/Activity/ActivityItem.js
  frontend/src/components/topbar/Header/Header.js
  frontend/src/components/topbar/Header/HeaderMenuButton.js
  frontend/src/components/topbar/TopbarTemplate.js
  frontend/src/containers/column/ColumnContainer.js
  frontend/src/containers/header/HeaderContainer.js
  frontend/src/containers/main/MainContainer.js
  frontend/src/containers/main/column/ColumnContainer.js
  frontend/src/containers/main/column/card/CardContainer.js
  frontend/src/containers/main/column/card/CardInputContainer.js
  frontend/src/containers/topbar/TopbarContainer.js
  frontend/src/containers/topbar/tempData.json
  frontend/src/lib/utility/util.js
Labels: FE

#38 [FE] Drag and drop with API
  frontend/src/containers/main/MainContainer.js
  frontend/src/containers/main/column/card/CardContainer.js
Labels: FE

#39 [FE] Activity - Apply API data
  frontend/src/components/topbar/Activity/Activity.js
  frontend/src/components/topbar/Activity/ActivityItem.js
  frontend/src/containers/topbar/TopbarContainer.js
  frontend/src/lib/utility/util.js
Labels: FE

#45 [FE] Add Column Update feature & Activity - Apply useContext
  frontend/src/App.js
  frontend/src/components/main/Main.js
  frontend/src/components/main/column/Column.js
  frontend/src/containers/main/MainContainer.js
  frontend/src/containers/main/column/ColumnContainer.js
  frontend/src/containers/main/column/card/CardContainer.js
  frontend/src/containers/main/column/card/CardInputContainer.js
  frontend/src/containers/topbar/TopbarContainer.js
  frontend/src/lib/utility/TodoStore.js
Labels: CSS, FE
